# Generated by Django 5.2.11 on 2026-03-19 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_options_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-id', '-created_at'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
