# Generated by Django 5.2.11 on 2026-03-23 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_tasks_assignee_attachments_comments_projects_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationTasks',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('task_manager.tasks',),
        ),
    ]
