# Generated by Django 5.2.11 on 2026-03-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_alter_tasks_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='is_reopened',
            field=models.BooleanField(default=False, verbose_name='Переоткрывалась ли'),
        ),
    ]
