# Generated by Django 5.2.11 on 2026-04-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0004_alter_tasks_options_alter_tasks_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachments',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='attachments', verbose_name='Фото'),
        ),
    ]
